version: '3.8'

services:
###> doctrine/doctrine-bundle ###
  webserver:
    image: nginx:alpine
    container_name: ${PROJECT_NAME}-webserver
    working_dir: /application
    restart: unless-stopped
    networks:
      - internal
    volumes:
      - ./:/application
      - ./docker/nginx:/etc/nginx/conf.d
    ports:
      - "${NGINX_PORT}:80"
    depends_on:
      - php-fpm

  php-fpm:
    build: docker/php-fpm
    container_name: ${PROJECT_NAME}-php-fpm
    restart: unless-stopped
    working_dir: /application
    environment:
      - PHP_WORKER_INSTALL_BCMATH=true
    volumes:
      - ./:/application
      - ./docker/php-fpm/php-ini-overrides.ini:/usr/local/etc/php/conf.d/99-overrides.ini
    networks:
      - internal

  database:
    image: postgres:13-alpine
    container_name: ${PROJECT_NAME}-postgres
    restart: unless-stopped
    env_file:
      - .env
    environment:
      PGPASSWORD: '${DB_PASSWORD}'
      POSTGRES_DB: '${DB_DATABASE}'
      POSTGRES_USER: '${DB_USERNAME}'
      # You should definitely change the password in production
      POSTGRES_PASSWORD: '${DB_PASSWORD}'
    volumes:
      - ./docker/postgres:/tmp
      - 'pg-data:/var/lib/postgresql/data'
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/postgresql/data:rw
    ports:
      - '${DB_PORT}:5432'
    networks:
      - internal

###< doctrine/doctrine-bundle ###

volumes:
  pg-data:
    driver: local
###> doctrine/doctrine-bundle ###
#  database_data:
###< doctrine/doctrine-bundle ###
networks:
  internal:
    driver: bridge
