framework:
  cache:
#    app: cache.adapter.filesystem
    app: cache.adapter.redis
    default_redis_provider: '%env(REDIS_URL)%'

    pools:
      api.cache:
#        adapter: cache.adapter.filesystem
        adapter: cache.adapter.redis
        provider: '%env(REDIS_URL)%'
        default_lifetime: 300

      user.cache:
#        adapter: cache.adapter.filesystem
        adapter: cache.adapter.redis
        provider: '%env(REDIS_URL)%'
        default_lifetime: 3600