framework:
  cache:
    app: cache.adapter.redis
    default_redis_provider: '%env(REDIS_URL)%'

    pools:
      api.cache:
        adapter: cache.adapter.redis
        provider: '%env(REDIS_URL)%'
        default_lifetime: 600

      user.cache:
        adapter: cache.adapter.redis
        provider: '%env(REDIS_URL)%'
        default_lifetime: 7200